### ISSUE TITLE
feat: Make repository a template repository

### ISSUE THREAD

**Issue by dumazy** [S-ecki/AdventOfCode-Starter-Dart#21]
Hi Simon,
I guess it's that time of the year again 😅 Hope you're all good!

Could we make this repository a "template repository"?
People can easily create their own repo from this without having to fork it.
<img width="620" alt="image" src="https://github.com/user-attachments/assets/f08a2212-b5ee-4258-a396-21150979e7b6">

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/b407b366-d47f-4be2-87f1-3f9d00837041">

**Comment by S-ecki** [comment]
Done, thanks for the idea!
