### ISSUE TITLE
Are you interested in a different implementation of Field

### ISSUE THREAD

**Issue by freemansoft** [S-ecki/AdventOfCode-Starter-Dart#26]
This implementation has Coordinate, RelativeCoordinate and Transition classes.  No tuples.

https://github.com/freemansoft/AdventOfCode-Dart/blob/2024/utils/board.dart

Are you interested in a PR or is the Field where you want it to be?

**Comment by S-ecki** [comment]
This looks great, especially moving away from tuples. Would definitely merge this
